### ISSUE TITLE
Tratamento de exceções

### ISSUE THREAD

**Issue by oliveiralex** [renansantos-25855/dsbootcamp-CrudClient#1]
Olá Renan, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.

O Trabalho foi aceito, parabéns! Porém, faltou fazer o tratamento de exceções. Está retornando erro 500 quando é informado um id que não existe. Tanto para buscar cliente pelo id, update e delete.

Abraço e bons estudos

**Comment by renansantos-25855** [comment]
Irei corrigir e reenviar o código. obrigado pelo feedback !



Enviado do meu Galaxy



-------- Mensagem original --------
De : Alexandre ***@***.***>
Data: 17/05/2021 14:54 (GMT-03:00)
Para: renansantos-25855/dsbootcamp-CrudClient ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [renansantos-25855/dsbootcamp-CrudClient] Tratamento de exceções (#1)


Olá Renan, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.

O Trabalho foi aceito, parabéns! Porém, faltou fazer o tratamento de exceções. Está retornando erro 500 quando é informado um id que não existe. Tanto para buscar cliente pelo id, update e delete.

Abraço e bons estudos

**Comment by renansantos-25855** [comment]
Boa tarde professor!! Quando puder dê uma olhada no meu github novamente, pois criei as exceções que estavam faltando.

Desde já, agradeço.                                                                                                                                                                    Renan Santos de Souza

________________________________
De: Alexandre ***@***.***>
Enviado: segunda-feira, 17 de maio de 2021 15:54
Para: renansantos-25855/dsbootcamp-CrudClient ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [renansantos-25855/dsbootcamp-CrudClient] Tratamento de exceções (#1)


Olá Renan, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.

O Trabalho foi aceito, parabéns! Porém, faltou fazer o tratamento de exceções. Está retornando erro 500 quando é informado um id que não existe. Tanto para buscar cliente pelo id, update e delete.

Abraço e bons estudos

**Comment by oliveiralex** [comment]
Olá Renan,
Conferi aqui e as correções foram realizadas! Parabéns
Faltou somente o UPDATE, ou seja, ao atualizar um cliente com id inexistente. 

Vou encerrar a issue ok?
Abraço
